import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "background":               "#181212",
        "surface":                  "#181212",
        "surface-dim":              "#181212",
        "surface-container-lowest": "#130d0d",
        "surface-container-low":    "#211a1a",
        "surface-container":        "#251e1e",
        "surface-container-high":   "#302828",
        "surface-container-highest":"#3b3333",
        "surface-bright":           "#403737",
        "on-background":            "#eedfdf",
        "on-surface":               "#eedfdf",
        "on-surface-variant":       "#e0bfbb",
        "primary":                  "#ffb3ae",
        "primary-fixed":            "#ffdad7",
        "primary-fixed-dim":        "#ffb3ae",
        "primary-container":        "#930616",
        "on-primary":               "#68000b",
        "on-primary-container":     "#ff9b95",
        "secondary":                "#ffb4ab",
        "secondary-fixed":          "#ffdad6",
        "secondary-fixed-dim":      "#ffb4ab",
        "secondary-container":      "#8d1515",
        "on-secondary":             "#690006",
        "on-secondary-container":   "#ff998f",
        "on-secondary-fixed":       "#410002",
        "on-secondary-fixed-variant":"#8d1515",
        "tertiary":                 "#c6c6c7",
        "tertiary-fixed":           "#e2e2e2",
        "tertiary-fixed-dim":       "#c6c6c7",
        "tertiary-container":       "#464848",
        "on-tertiary":              "#2f3131",
        "on-tertiary-fixed":        "#1a1c1c",
        "on-tertiary-fixed-variant":"#454747",
        "on-tertiary-container":    "#b6b6b7",
        "outline":                  "#a88a86",
        "outline-variant":          "#59413e",
        "inverse-surface":          "#eedfdf",
        "inverse-on-surface":       "#372e2e",
        "inverse-primary":          "#b4252a",
        "surface-tint":             "#ffb3ae",
        "surface-variant":          "#3b3333",
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
        "on-primary-fixed":         "#410004",
        "on-primary-fixed-variant": "#920516",
      },
      borderRadius: {
        DEFAULT: "0px",
        sm:      "0px",
        md:      "0px",
        lg:      "0px",
        xl:      "0px",
        "2xl":   "0px",
        "3xl":   "0px",
        full:    "9999px",
      },
      fontFamily: {
        headline: ["Epilogue", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Inter", "sans-serif"],
      },
      transitionTimingFunction: {
        "spring": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [],
} satisfies Config;
